import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="stylesheet" href="https://use.typekit.net/rlz0dln.css"/> */}
      </Head>

      <main className={styles.main}>
        <nav>
          <div className={styles.navWrapper}>
            <div className={styles.logoWrapper}>
              <img src="/salmon.png" alt="salmon" width={145} height={55} />
              <h2 style={{ marginLeft: 15, fontSize: 40 }}>Salmon Cookies</h2>
            </div>
            <Link href="/sales">
              <a>Sales Page</a>
            </Link>
          </div>
        </nav>

        <section>
          <h2 style={{ textAlign: "center" }}>
            Best Salmon Cookies This Side of the Rockies
          </h2>
          <div style={{display: "flex", alignItems: "center", justifyContent: "center", marginTop: 50, backgroundColor: "#f7f7eb"}}>
            <div>
              <ol>
                <li>Where to Find Us </li>
                <li>1 Way, Unit 21, Seattle, WA</li>
                <li>8 This Way, Unit 17-38, Tokyo, JP</li>
                <li>100 Away, Unit 11-32, San Diego, CA</li>
              </ol>
            </div>
            <div>
              <ol>
                <li> Hours of Operations </li>
                <li>Monday 6am to 7pm</li>
                <li>Tuesday 6am to 7pm</li>
                <li>Wednesday 6am to 7pm</li>
                <li>Thursday 6am to 7pm</li>
                <li>Friday 6am to 7pm</li>
                <li>Saturday 6am to 7pm</li>
                <li>Sunday 6am to 7pm</li>
              </ol>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
